new5/app1/urls.py
from django.contrib import admin
from django.conf.urls import url

from app1 import views
app_name="app1"
urlpatterns = [

    url(r'^$', views.home, name="home"),
    url(r'^index/$', views.index, name="index"),

    url(r'list/$', views.studentlist, name="list"),
    url(r'form1/$', views.form1, name="form1"),
    url(r'form2/$', views.form2, name="form2"),
    url(r'form3/$', views.form3, name="form3"),
url(r'fact/$', views.fact, name="fact"),

]

new5/app2/urls.py
from django.contrib import admin
from django.conf.urls import url
app_name="app2"
from app2 import views
urlpatterns = [

    url(r'^first/$', views.first, name="first"),
    url(r'^second/$', views.second, name="second"),
]

new5/new/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from app2 import views
from app1 import views
urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.rel, name="rel"),

    url(r'^app1/', include('app1.urls')),
    url(r'^app2/', include('app2.urls')),

]

new5/app1/models.py
from django.db import models


class student(models.Model):  # Table Definition
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    def __str__(self):
        return self.name

new5/app2/models.py
from django.db import models

# Create your models here.

new5/app1/forms.py
from django import forms
from app1.models import student
class studentform(forms.ModelForm):  #Form Definition
    class Meta:
        model=student
        fields='__all__'

new5/app1/views.py
from django.shortcuts import render
from app1.models import student
from app1.forms import studentform
from django.http import HttpResponse
def home(request):

    return render(request,"home.html",{'name':"saranya",'age':21})


def index(request):
    return render(request,"index.html")

def rel(request):
    return render(request,"relative.html")

def studentlist(request):
    k=student.objects.all()
    return render(request,'list.html',{'s':k})

def form1(request):  #First Method
    form=studentform()  # empty form object
    if(request.method=="POST"):
        form=studentform(request.POST)
        if(form.is_valid()):
            form.save()
            return studentlist(request)


    return render(request,'form1.html',{'form':form})

def form2(request):
    if (request.method == "POST"):
        form = studentform(request.POST)
        if (form.is_valid()):
            form.save()
            return studentlist(request)

    return render(request,'form2.html')

def form3(request):
    if (request.method == "POST"):
        n=request.POST['n']
        a=request.POST['a']
        s=student.objects.create(name=n,age=a)
        s.save()
        return studentlist(request)

    return render(request, 'form3.html')

def fact(request):
    if(request.method=="POST"):
        n=int(request.POST['n'])
        fact=1
        for i in range(1,n+1):
            fact=fact*i
        return render(request,'fact.html',{'f':fact})

    return render(request,'fact.html')

new5/app2/views.py
from django.http import HttpResponse
from django.shortcuts import render
def first(request):
    return render(request,'first.html')


def second(request):
    return HttpResponse("Python")

new5/templates/fact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<div class="container">
<h1>Factorial Of a Number</h1>
<form method="POST">
    {% csrf_token %}
<div class="form-group">
      <label >Number:</label>
      <input type="text" class="form-control" name="n">
    </div>



<input type="submit">
    </form>
    {% if f %}
    <h1>Factorial is {{f}}</h1>
    {% endif %}
   </div>
</body>
</html>

new5/templates/first.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<h1>First Page</h1>

</body>
</html>

new5/templates/form1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<center>
<h1>ADD STUDENT DETAILS-Built in Method</h1>
<form method="POST">
    {% csrf_token %}

{{form.as_p}}

<input type="submit">
    </form>
    </center>
</body>
</html>

new5/templates/form2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<div class="container">
<h1>ADD STUDENT DETAILS-User Defined(using form object)</h1>
<form method="POST">
    {% csrf_token %}
<div class="form-group">
      <label >Name:</label>
      <input type="text" class="form-control" name="name">
    </div>
    <div class="form-group">
      <label>Age:</label>
      <input type="text" class="form-control" name="age">
    </div>


<input type="submit">
    </form>
   </div>
</body>
</html>

new5/templates/form3.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<div class="container">
<h1>ADD STUDENT DETAILS-User Defined(without using form object)</h1>
<form method="POST">
    {% csrf_token %}
<div class="form-group">
      <label >Name:</label>
      <input type="text" class="form-control" name="n">
    </div>
    <div class="form-group">
      <label>Age:</label>
      <input type="text" class="form-control" name="a">
    </div>


<input type="submit">
    </form>
   </div>
</body>
</html>

new5/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body style="background-image:url('{% static "images/m.jpg" %}');background-repeat:no-repeat;">
<h1>HOME PAGE</h1>
<h1>My name is {{name}}</h1>
<p>Age is {{age}}</p>

</body>
</html>

new5/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<h1>IndexPAge</h1>
<img src="{% static 'images/d.jpg' %}">
</body>
</html>

new5/templates/list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<h1>Student Details</h1>
<table class="table table-bordered">
    <tr class="primary">
        <th>Name</th>
        <th>Age</th>
    </tr>

    {% for i in s %}
    <tr class="primary">
        <td>{{i.name}}</td>
         <td>{{i.age}}</td>
    </tr>
    {% endfor %}
</table>
<br>
<br>
<h1>Student Details</h1>
<ol>

    {% for i in s %}
    <li>Student Info</li>
    <ul>
        <li>Name:{{i.name}}</li>
         <li>Age:{{i.age}}</li>
    </ul>
    {% endfor %}
</ol>
</body>
</html>

new5/templates/relative.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/a.css' %}">
</head>
<body>
<a class="btn btn-danger btn-md" href="{% url 'app1:home' %}">Link to home page</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a class="btn btn-danger btn-md" href="{% url 'app1:index' %}">Link To Index</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a class="btn btn-danger btn-md" href="{% url 'app2:first' %}">Link To First Page</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a class="btn btn-danger btn-md" href="{% url 'app1:form2' %}">Add Studentdetails</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a class="btn btn-danger btn-md" href="{% url 'app1:list' %}">View Studentdetails</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a class="btn btn-danger btn-md" href="{% url 'app1:fact' %}">Factorial Of aNumber</a>&nbsp;&nbsp;&nbsp;&nbsp;
</body>
</html>